name: Build C++ for All OS

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile program
        run: |
          g++ program.cpp -o program
          if [ "$RUNNER_OS" == "Windows" ]; then mv program program.exe; fi

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: program-${{ matrix.os }}
          path: program*
