name: Build Server and Client for All OS

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile server
        run: |
          g++ server.cpp -o server
          if [ "$RUNNER_OS" == "Windows" ]; then mv server server.exe; fi

      - name: Compile client
        run: |
          g++ client.cpp -o client
          if [ "$RUNNER_OS" == "Windows" ]; then mv client client.exe; fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: program-${{ matrix.os }}
          path: server* client*